### ISSUE TITLE
[Feature] some sort of manual

### ISSUE THREAD

**Issue by nate-4000** [northwesttrees-gaming/CCTV-Craft#27]
### Suggestion or Feature

make a manual because i cant figure out how to do anything regarding drones

### Core Features

- some sort of manual index
- a page on most blocks

### Reason For Feature

i cant figure things out

**Comment by northwesttreesgaming** [comment]
Everything is documented on this repositories wiki.
[https://github.com/northwesttrees-gaming/CCTV-Craft/wiki](Wiki Tab)
